@startuml AdapterPattern
hide empty members

class Client{
}

interface Target{
}

interface Adapter{
}

interface Adaptee{
}

class ObjectAdapter{
    - Adaptee adaptee
}

class ClassAdapter{
}

class ConcreteAdaptee{
}

Client -right- Target: > use
Target <|-down- Adapter
Adapter <|-right- ObjectAdapter
Adaptee <|-down-ConcreteAdaptee
Target <|-right- ClassAdapter
ConcreteAdaptee <|-- ClassAdapter
ObjectAdapter -- Adaptee: < composite
@enduml