@startuml

interface Pizza{
    name
    dough
    sauce
    toppings
    
    prepare()
    bake()
    cut()
    box()
    toString()
}

interface PizzaStore{
    createPizza()
    orderPizza()
}

Pizza <|-- ChicagoStyleCheesePizza
Pizza <|-- ChicagoStyleClamPizza
Pizza <|-- ChicagoStylePepperoniPizza
Pizza <|-- ChicagoStyleVeggiePizza
Pizza <|-- NYStyleCheesePizza
Pizza <|-- NYStyleClamPizza
Pizza <|-- NYStylePepperoniPizza
Pizza <|-- NYStyleVeggiePizza

PizzaStore <|-- ChicagoPizzaStore
PizzaStore <|-- NYPizzaStore

@enduml