@startuml

hide empty members

abstract class Subject{
    registerPushObserver(self, observer)
    removePushObserver(self, observer)
    registerPullObserver(self, observer)
    removePullObserver(self, observer)
    {abstract} notifyPushObserver(self)
    notifyPullObserver(self)
    notifyObserver(self)
    hasChange(self)
}

class WeatherData{
    float temperature
    float humidity
    float pressure
    simulateChange(self, newTemperature, newHumidity, newPressure)
}

abstract class Observer{
    {abstract} update(self, *args)
}

class CurrentConditionsDisplay{
    float temperature
    float humidity
    display(self)
}

class StatisticsDisplay{
    float avgTemperature
    float maxTemperature
    float minTemperature
    display(self)
}

class ForecastDisplay{
    float currentPressure
    float lastPressure
    display(self)
}

Subject <|-- WeatherData

Observer <|-- CurrentConditionsDisplay
Observer <|-- StatisticsDisplay
Observer <|-- ForecastDisplay

Subject "1" - "many" Observer : < register 

@enduml