@startuml example
hide empty members

class CarManager{
    - {static} CarManager carManager
    - {static} int carSequence
    - int carNumber
    - int waitForDestroyed
    - Queue<Car> availableCar
    - Set<Car> dispatchedCar
    
    + {static} CarManager getInstance()
    - CarManager()
    + int getCarNumber()
    + void setCarNumber(int carNumber)
    + int getAvailableNumber()
    + Car rentCar()
    + Car returnCar(Car car)
}

class Car{
    - int carNo

    + Car(int carNo)
    + void drive(int clientNo)
    + int getCarNo()
}

@enduml

