@startuml
interface Invoker{
    commands
}

interface Command{
    execute()
    undo()
}



Invoker *-- Command
Invoker <|-- RemoteControlWithUndo

Command <|-- NoCommand
Command <|-- CeilingFanCommand
Command <|-- LightCommand

CeilingFanCommand <|-- CeilingFanHighCommand
CeilingFanCommand <|-- CeilingFanLowCommand
CeilingFanCommand <|-- CeilingFanMediumCommand
CeilingFanCommand <|-- CeilingFanOffCommand
CeilingFanCommand *-- CeilingFan

LightCommand <|-- DimmerLightOffCommand
LightCommand <|-- DimmerLightOnCommand
LightCommand <|-- LightOffCommand
LightCommand <|-- LightOnCommand
LightCommand *-- Light


@enduml