@startuml DecoratorPattern
hide empty members

abstract class Beverage{
    description
    {abstract} cost(self)
}

class Espresso{
    cost(self)
}

class HouseBlend{
    cost(self)
}

class DarkRoast{
    cost(self)
}

class Decaf{
    cost(self)
}

class Condiment{
    beverage
}

class Milk{
    cost(self)
}

class Mocha{
    cost(self)
}

class Soy{
    cost(self)
}

class Whip{
    cost(self)
}

Beverage <|-- BaseBeverage
Beverage <|-- Condiment

BaseBeverage <|-- Espresso
BaseBeverage <|-- HouseBlend
BaseBeverage <|-- DarkRoast
BaseBeverage <|-- Decaf

Condiment <|-- Milk
Condiment <|-- Mocha
Condiment <|-- Soy
Condiment <|-- Whip

@enduml