@startuml
class GumballMachine{
    count
    insertQuarter()
    ejectQuarter()
    turnCrank()
    releaseBall()
    refill()
}

interface State{
    insertQuarter()
    ejectQuarter()
    turnCrank()
    dispense()
    refill()
}

State <|-- HasQuarterState
State <|-- NoQuarterState
State <|-- SoldOutState
State <|-- SoldState
State <|-- WinnerState

GumballMachine *-- HasQuarterState
GumballMachine *-- NoQuarterState
GumballMachine *-- SoldOutState
GumballMachine *-- SoldState
GumballMachine *-- WinnerState

@enduml
