@startuml example
hide empty members


interface Streamer{
    String accountInfo
    registerObserver()
    removeObserver()
    notifyObserver()
    getIsStreaming()
    setIsStreaming()
}

interface Audience{
    update()
}

class TwitchStreamer{
    String accountInfo
    registerObserver()
    removeObserver()
    notifyObserver()
    getIsStreaming()
    setIsStreaming()
}

class TwitchAudience{
    accountID
    nickname
    update()
    equals()
}

Streamer <|-- TwitchStreamer
Audience <|-- TwitchAudience

Streamer "1" - "0..*" Audience : < register 

@enduml

