@startuml

interface Subject{
    registerObserver()
    removeObserver()
    notifyObserver()
    hasChange()
}

interface Observer{
    subject
    __ abstract __
    update()
}

Subject <|-- WeatherData

Observer <|-- CurrentConditionsDisplay
Observer <|-- StatisticsDisplay
Observer <|-- ForecastDisplay

Observer o-- Subject

@enduml