@startuml ObserverPattern
hide empty members

interface Subject{
    + registerObserver()
    + removeObserver()
    + notifyObserver()
}

interface Observer{
    + update()
}

Subject "1" - "0..*" Observer : < register 
@enduml