@startuml

HomeTheaterFacade *-- Amplifier
HomeTheaterFacade *-- CdPlayer
HomeTheaterFacade *-- DvdPlayer
HomeTheaterFacade *-- PopcornPopper
HomeTheaterFacade *-- Projector
HomeTheaterFacade *-- Screen
HomeTheaterFacade *-- TheaterLights
HomeTheaterFacade *-- Tuner

@enduml