@startuml StrategyPattern
hide empty members

class Contex{
    + Strategy strategy
    + invokeStrategyMethod()
}

interface Strategy{
    + strategyMethod()
}

class ConcreteStrategy1{
    + strategyMethod()
}

class ConcreteStrategy2{
    + strategyMethod()
}

Contex o-- Strategy
Strategy <|-- ConcreteStrategy1
Strategy <|-- ConcreteStrategy2

@enduml