@startuml StrategyPattern
hide empty members

class Contex{
    + Strategy strategy
    + invokeStrategyMethod()
}

interface Strategy{
    + strategyMethod()
}

class ConcreteStrategyA{
}

class ConcreteStrategyB{
}


Contex *-- Strategy
Strategy <|-- ConcreteStrategyA
Strategy <|-- ConcreteStrategyB

@enduml