@startuml
interface Duck{
    fly_behavior
    quack_behavior
    
    performQuack()
    performFly()
    swim()
    display()
}

interface FlyBehavior{
    fly()
}

interface QuackBehavior{
    fly()
}

Duck *-- FlyBehavior
Duck *-- QuackBehavior

FlyBehavior <|-- FlyWithWings
FlyBehavior <|-- FlyNoWay
FlyBehavior <|-- FlyRocketPowered

QuackBehavior <|-- Quack
QuackBehavior <|-- Squack
QuackBehavior <|-- MuteQuack

@enduml