@startuml

interface Duck{
    quack()
    fly()
}

interface Turkey{
    gobble()
    fly()
}

Duck <|-- MallardDuck
Duck <|-- TurkeyAdapter
Duck <|-- TurkeyAdapter2

MallardDuck <|-- DuckAdapter2

Turkey <|-- WildTurkey
Turkey <|-- DuckAdapter
Turkey <|-- DuckAdapter2

WildTurkey <|-- TurkeyAdapter2

DuckAdapter *-- Duck

TurkeyAdapter *-- Turkey

@enduml