@startuml AbstractFactoryPattern
hide empty members

class Client{
}

interface AbstractFactory{
    + createProductA()
    + createProductB()
}

interface ProductA{
}

interface ProductB{
}

AbstractFactory -left- ProductA : > produce 
AbstractFactory - ProductB : > produce 

Client -down- AbstractFactory : > use
Client -down- ProductA : > dependent
Client -down- ProductB : > dependent
@enduml