@startuml example
hide empty members

interface Ingredient{
    + String getInfo()
}

interface Dough{
    + String getInfo()
}

class ThickCrustDough{
    + String getInfo()
}

class ThinCrustDough{
    + String getInfo()
}

interface Cheese{
    + String getInfo()
}

class ReggianoCheese{
    + String getInfo()
}

class MozzarellaCheese{
    + String getInfo()
}


interface Pepperoni{
    + String getInfo()
}

class SlicedPepperoni{
    + String getInfo()
}

enum PizzaType{
    + CHEESE_PIZZA
}

interface Pizza{
    + List<Ingredient> ingredients

    + String getName()
    + String showIngredients()
}

interface CheesePizza{
    + List<Ingredient> ingredients
    + Cheese cheese 
    
    + String getName()
    + String showIngredients()
}

class CheesePizzaOfStoreA{
    + List<Ingredient> ingredients
    + Cheese cheese 
    
    + CheesePizzaOfStoreA(Cheese cheese, List<Ingredient> ingredients)
    
    + String getName()
    + String showIngredients()
}


class CheesePizzaOfStoreB{
    + List<Ingredient> ingredients
    + Cheese cheese 
    
    + CheesePizzaOfStoreB(Cheese cheese, List<Ingredient> ingredients)

    + String getName()
    + String showIngredients()
}

interface IngredientFactory{
    + Dough createDough()
    + Cheese createCheese()
    + Pepperoni createPepperoni()
}

class IngredientFactoryOfStoreA{
    + Dough createDough()
    + Cheese createCheese()
    + Pepperoni createPepperoni()
}

class IngredientFactoryOfStoreB{
    + Dough createDough()
    + Cheese createCheese()
    + Pepperoni createPepperoni()
}

abstract class PizzaStore{
    + IngredientFactory ingredientFactory
    + Pizza orderPizza()
}

class PizzaStoreA{
    + IngredientFactory ingredientFactory
    + Pizza orderPizza()
}

class PizzaStoreB{
    + IngredientFactory ingredientFactory
    + Pizza orderPizza()
}

Ingredient <|-- Dough
Ingredient <|-- Cheese
Ingredient <|-- Pepperoni

Dough <|-- ThickCrustDough
Dough <|-- ThinCrustDough

Cheese <|-- ReggianoCheese
Cheese <|-- MozzarellaCheese

Pepperoni <|-- SlicedPepperoni

Pizza <|-- CheesePizza

CheesePizza <|-- CheesePizzaOfStoreA
CheesePizza <|-- CheesePizzaOfStoreB

IngredientFactory <|-- IngredientFactoryOfStoreA
IngredientFactory <|-- IngredientFactoryOfStoreB

PizzaStore <|-- PizzaStoreA
PizzaStore <|-- PizzaStoreB

IngredientFactory - Ingredient : > produce
Pizza *-left- Ingredient 
PizzaStore *- IngredientFactory

@enduml

