@startuml FactoryMethodPattern
hide empty members

abstract class Creator{
    + {abstract} factoryMethod()
}

class ConcreteCreator1{
    + factoryMethod()
}

class ConcreteCreator2{
    + factoryMethod()
}

interface Product{
}

class ConcreteProduct1{
}

class ConcreteProduct2{
}

Creator <|-- ConcreteCreator1
Creator <|-- ConcreteCreator2
Product <|-- ConcreteProduct1
Product <|-- ConcreteProduct2

Creator - Product : > produce 
@enduml