@startuml DecoratorPattern
hide empty members

interface Component{
    + aMethod()
} 

interface BaseComponent{
    + aMethod()
}

interface Decorator{
    - Component component
    + Decorator(Component component)
    + aMethod()
}

class ConcreteBaseComponentA{
}

class ConcreteBaseComponentB{
}

class ConcreteDecoratorA{
}

class ConcreteDecoratorB{
}

Component <|-- BaseComponent
Component <|-- Decorator
BaseComponent <|-- ConcreteBaseComponentA
BaseComponent <|-- ConcreteBaseComponentB
Decorator <|-- ConcreteDecoratorA
Decorator <|-- ConcreteDecoratorB

@enduml