@startuml DecoratorPattern
hide empty members

interface Component{
    + aMethod()
} 

interface BaseComponent{
    + aMethod()
}

interface Decorator{
    - Component component
    + Decorator(Component component)
    + aMethod()
}

Component <|-- BaseComponent
Component <|-- Decorator

@enduml