@startuml example
hide empty members

interface Beverage{
    getPrice()
    getgetCost()
    getProfit()
} 

interface Coffee{
    getPrice()
    getCost()
    getProfit()
}

class HouseBlend{
    getPrice()
    getCost()
    getProfit()
}

class DarkRoast{
    getPrice()
    getCost()
    getProfit()
}

interface Condiment{
    Beverage beverage
    getPrice()
    getCost()
    getProfit()
}

class Milk{
    Beverage beverage
    getPrice()
    getCost()
    getProfit()
}

class Mocha{
    Beverage beverage
    getPrice()
    getCost()
    getProfit()
}

Beverage <|-- Coffee
Coffee <|-- HouseBlend
Coffee <|-- DarkRoast

Beverage <|-- Condiment
Condiment <|-- Milk
Condiment <|-- Mocha

@enduml