@startuml example
hide empty members

interface Beverage{
    + int getPrice()
    + int getgetCost()
    + int getProfit()
} 

interface Coffee{
    + int getPrice()
    + int getCost()
    + int getProfit()
}

class HouseBlend{
    + int getPrice()
    + int getCost()
    + int getProfit()
}

class DarkRoast{
    + int getPrice()
    + int getCost()
    + int getProfit()
}

interface Condiment{
    - Beverage beverage
    + Beverage getBeverage()
    + int getPrice()
    + int getCost()
    + int getProfit()
}

class Milk{
    - Beverage beverage
    + Milk(Beverage beverage)
    + int getPrice()
    + int getCost()
    + int getProfit()
}

class Mocha{
    - Beverage beverage
    + Mocha(Beverage beverage)
    + int getPrice()
    + int getCost()
    + int getProfit()
}

Beverage <|-- Coffee
Coffee <|-- HouseBlend
Coffee <|-- DarkRoast

Beverage <|-- Condiment
Condiment <|-- Milk
Condiment <|-- Mocha

@enduml