@startuml

hide empty members

abstract class Duck{
    quack : a QuackBehavior function
    fly : a FlyBehavior function
    swim(self)
    {abstract} display(self)
}

Duck <|-- MallardDuck
Duck <|-- ModelDuck

@enduml