@startuml

hide empty members

abstract class Duck{
    fly(*args, **kwargs)
    quack(*args, **kwargs)
    setFly(self, flyBehavior)
    setQuack(self, quackBehavior)
    swim(self)
    {abstract} display(self)
}

Duck <|-- MallardDuck
Duck <|-- ModelDuck

@enduml